### ISSUE TITLE
The question about the type of SwinTransfomer

### ISSUE THREAD

**Issue by super233** [FZfangzheng/Swin-Transformer-Semantic-Segmentation-Without-mmsegmentation#1]
Hi, thanks for your awesome code.

Which type is this SwinTransformer, Swin-T, Swin-S or Swin-B? And how can I modify code to use one of them?

**Comment by FZfangzheng** [comment]
Hi, this is Swin-B.
You can choose different types by modifying the relevant parameters in /swin_transformer/backbones/swin_transformer.py#L478.
For parameters, please refer to the configuration in /configs/swin in the official code.

**Comment by super233** [comment]
Thanks very much. :-)
